
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/teste?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: root
    password: neres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true